#ifndef EXTERNAL_DATABLOCK_H_
#define EXTERNAL_DATABLOCK_H_

#define SYSTEM_IMG_SOURCE_GLOBAL_BLOCKING 0
#define SYSTEM_IMG_SINK_GLOBAL_BLOCKING 0
#define DIMX_GLOBAL_BLOCKING 0
#define DIMY_GLOBAL_BLOCKING 0
#define OUTPUTIMAGE_BLOCKING 0
#define INPUTIMAGE_BLOCKING 0

#endif 

