package demo;

/**
 * create fiodl file
 */
@SuppressWarnings("all")
public class test2 {
  public static void main(final String[] args) {
    throw new Error("Unresolved compilation problems:"
      + "\nForSyDeSystemGraph cannot be resolved to a type."
      + "\nForSyDeSystemGraph cannot be resolved."
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\nForSyDeModelHandler cannot be resolved."
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCHANNEL cannot be resolved"
      + "\nDECISION_SDF_BOUNDEDSDFCHANNEL cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nIMPL_TOKENIZABLEDATABLOCK cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nTYPING_DATATYPES_DOUBLE cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nIMPL_ANSICBLACKBOXEXECUTABLE cannot be resolved"
      + "\nTYPING_TYPEDOPERATION cannot be resolved"
      + "\nIMPL_INSTRUMENTEDEXECUTABLE cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nMOC_SDF_SDFDATAEDGE cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nMOC_SDF_SDFDATAEDGE cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nTYPING_DATATYPES_DATADEFINITION cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nwriteModel cannot be resolved");
  }
}
