package demo;

@SuppressWarnings("all")
public class test4 {
  public static void main(final String[] args) {
    throw new Error("Unresolved compilation problems:"
      + "\nForSyDeSystemGraph cannot be resolved to a type."
      + "\nForSyDeSystemGraph cannot be resolved."
      + "\nThe method or field EdgeTrait is undefined"
      + "\nForSyDeModelHandler cannot be resolved."
      + "\nForSyDeModelHandler cannot be resolved."
      + "\nThe method addVertex(ForSyDeSystemGraph) from the type test4 refers to the missing type Object"
      + "\nThe method addchannel(ForSyDeSystemGraph) from the type test4 refers to the missing type ForSyDeSystemGraph"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nThe method connectChannel(ForSyDeSystemGraph, String, String, String, String, EdgeTrait) from the type test4 refers to the missing type Object"
      + "\nMOC_SDF_SDFDATAEDGE cannot be resolved"
      + "\nwriteModel cannot be resolved"
      + "\nwriteModel cannot be resolved");
  }
  
  public static Object connectChannel(final /* ForSyDeSystemGraph */Object model, final String srcname, final String dstname, final String srcport, final String dstport, final /* EdgeTrait */Object t) {
    throw new Error("Unresolved compilation problems:"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved");
  }
  
  public static void addchannel(final /* ForSyDeSystemGraph */Object model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCHANNEL cannot be resolved"
      + "\nDECISION_SDF_BOUNDEDSDFCHANNEL cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nIMPL_TOKENIZABLEDATABLOCK cannot be resolved"
      + "\naddVertex cannot be resolved");
  }
  
  public static Object addVertex(final /* ForSyDeSystemGraph */Object model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nThe method or field VertexProperty is undefined"
      + "\nVertex cannot be resolved."
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\nThe method or field EdgeTrait is undefined"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nMOC_SDF_SDFCOMB cannot be resolved"
      + "\nDECISION_SDF_PASSEDSDFCOMB cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nTYPING_DATATYPES_INTEGER cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\nproperties cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\naddTraits cannot be resolved"
      + "\nIMPL_ANSICBLACKBOXEXECUTABLE cannot be resolved"
      + "\nTYPING_TYPEDOPERATION cannot be resolved"
      + "\nIMPL_INSTRUMENTEDEXECUTABLE cannot be resolved"
      + "\naddVertex cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nTYPING_DATATYPES_DATADEFINITION cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nTYPING_DATATYPES_DATADEFINITION cannot be resolved"
      + "\nconnect cannot be resolved"
      + "\nqueryVertex cannot be resolved"
      + "\nget cannot be resolved"
      + "\nTYPING_DATATYPES_DATADEFINITION cannot be resolved");
  }
}
