package template.rtos;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class StartTaskTemplateSrcRTOS {
  public String create() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Define Task Stack");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("StackType_t task_StartTask_stk[TASK_STACKSIZE]; ");
    _builder.newLine();
    _builder.append("StaticTask_t tcb_start;");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Declare Extern Task Stack");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("*/\t\t");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Declare Message Queue");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("*/\t");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Declare Extern Software Timer and Semaphore");
    _builder.newLine();
    _builder.append("=================================================");
    _builder.newLine();
    _builder.append("*/\t");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.newLine();
    _builder.append("void start_task(){");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Initilize Message Queue     */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Initilize Software Timer    */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Initilize Timer\'s Semaphore */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Initilize Actor Tasks       */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Start Software Timer        */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Delete start task           */");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
}
